// File: D:\SkillSynth\src\frontend\app\layout.tsx

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// 1. استيراد (import) مكون Header الذي أنشأناه
import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar" dir="rtl"> {/* أضفنا اللغة العربية والاتجاه من اليمين لليسار */}
      <body className={inter.className}>
        {/* 2. نضع المكون هنا. سيمرر اسم مستخدم وهمي مؤقتاً */}
        <Header userName="زائر" />

        {/* 3. {children} يمثل محتوى الصفحة الحالية (سواء كانت dashboard أو wizard أو غيرها) */}
        {/* main يضيف تنسيقاً لترك مساحة حول المحتوى الرئيسي */}
        <main className="container mx-auto p-4">
          {children}
        </main>
      </body>
    </html>
  );
}