# src/backend/routers/paths_router.py

import json
from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session
from typing import List

from backend import crud, models, schemas, auth
from backend.database import get_db
from data.learning_paths.assessor import run_assessment
from data.learning_paths.generator import generate_path

router = APIRouter()

@router.post("/generate-path/", response_model=schemas.Path)
def generate_new_path(
    path_input: schemas.GeneratePathInput,
    db: Session = Depends(get_db),
    current_user: models.Profile = Depends(auth.get_current_user)
):
    try:
        # 1. استدعاء وحدة التقييم
        skill_profile = run_assessment(goal=path_input.goal, user_answers=path_input.answers)
        
        # 2. حفظ بروفايل المهارات
        crud.update_profile(db, profile_id=current_user.id, profile_data=schemas.ProfileUpdate(skill_profile=skill_profile))

        # --- التحصين الإضافي ---
        # نقوم بتجهيز مفتاح الهدف ليكون متوافقًا مع ملفات JSON
        goal_key = path_input.goal.lower().replace(" ", "_")

        # 3. استدعاء مولد المسارات
        generated_data = generate_path(
            profile=skill_profile,
            goal=goal_key, # <-- نستخدم المفتاح المعدل
            weekly_hours=path_input.weekly_hours,
            preferences=path_input.preferences.dict()
        )
        if "error" in generated_data:
            raise HTTPException(status_code=400, detail=f"Path generation error: {generated_data['error']}")
        
        # 4. حفظ المسار بالكامل في قاعدة البيانات
        db_path = crud.create_path_for_profile(db, title=generated_data.get('path_title', 'Generated Path'), description=generated_data.get('metadata', {}).get('description', 'Path generated by AI'), profile_id=current_user.id)
        
        for step_data in generated_data.get('steps', []):
            db_step = models.PathStep(step_number=step_data.get('index'), title=step_data.get('title'), content=json.dumps(step_data.get('resource')) if step_data.get('resource') else None, path_id=db_path.id)
            db.add(db_step)
        
        db.commit()
        db.refresh(db_path)
        
        return db_path

    except Exception as e:
        print(f"!!! CRITICAL ERROR in generate_path endpoint: {e}")
        db.rollback() 
        raise HTTPException(status_code=500, detail=f"An internal error occurred in the AI module: {str(e)}")


@router.get("/paths/{path_id}", response_model=schemas.Path)
def read_single_path(path_id: int, db: Session = Depends(get_db), current_user: models.Profile = Depends(auth.get_current_user)):
    db_path = crud.get_path_by_id(db, path_id=path_id, profile_id=current_user.id)
    if db_path is None:
        raise HTTPException(status_code=404, detail="Path not found")
    return db_path


@router.get("/paths/", response_model=List[schemas.Path])
def read_paths_for_current_user(db: Session = Depends(get_db), current_user: models.Profile = Depends(auth.get_current_user)):
    return crud.get_paths_by_profile(db, profile_id=current_user.id)